version: "3.8"

services:
  web:
    build: .
    container_name: avtoteker-dev-web
    volumes:
      - ./mysite:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET=j56@jyc()*qnyl1vj^yf5_a5c27kfp5ysf^yeoxl#ul4hn^j^(
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3151936f
    depends_on:
      - db

  db:
    container_name: avtoteker-dev-db
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=avtoteker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3151936f
    volumes:
      - dev-pgdata:/var/lib/postgresql/data/

volumes:
  dev-pgdata:
