version: "3.8"

services:
  wheel-size:
    container_name: avto-node-ws
    build:
      context: ./node
    environment:
      - WHEEL_SIZE_KEY=5f0e624a880add6bc70e73f774ae3db6

  web:
    restart: on-failure
    container_name: avtoteker-web
    build: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET=j56@jyc()*qnyl1vj^yf5_a5c27kfp5ysf^yeoxl#ul4hn^j^(
      - POSTGRES_DB=avtoteker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3151936f
      - DEBUG=0
      - ALLOWED_HOSTS=127.0.0.1,localhost,68.183.147.145,avtoteker.az,www.avtoteker.az
    depends_on:
      - db

  proxy:
    restart: on-failure
    container_name: avtoteker-proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - web

  db:
    restart: on-failure
    container_name: avtoteker-db
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=avtoteker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3151936f
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  static_data:
  pgdata:
