version: "3.8"

services:
  web:
    restart: on-failure
    container_name: avtoteker-web
    build: .
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    environment:
      - SECRET=j56@jyc()*qnyl1vj^yf5_a5c27kfp5ysf^yeoxl#ul4hn^j^(
      - POSTGRES_DB=avtoteker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3151936f
      - DEBUG=1
      - ALLOWED_HOSTS=127.0.0.1,localhost,68.183.147.145
    depends_on:
      - db

  proxy:
    container_name: avtoteker-proxy
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    ports:
      - "8080:8080"
    depends_on:
      - web

  db:
    container_name: avtoteker-db
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=avtoteker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3151936f
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  static_data:
  media_data:
  pgdata:
