# Generated by Django 3.1 on 2021-04-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_navigationlink_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationlink',
            name='show_in_navigation',
        ),
    ]
