# Generated by Django 3.1 on 2021-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_auto_20210609_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
