# Generated by Django 3.1 on 2020-09-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="serie",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
