# Generated by Django 3.1 on 2020-09-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0002_auto_20200904_2120"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brand",
            old_name="descroiption",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="serie",
            old_name="descroiption",
            new_name="description",
        ),
    ]
