# Generated by Django 3.1 on 2020-09-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0003_auto_20200905_0924"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="specific.country"
            ),
        ),
        migrations.AlterField(
            model_name="serie",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="specific.brand"
            ),
        ),
    ]
