# Generated by Django 3.1 on 2020-10-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0008_remove_brand_order_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="order_number",
            field=models.IntegerField(default=1),
        ),
    ]
