# Generated by Django 3.1 on 2020-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0009_brand_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="serie",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
