# Generated by Django 3.1 on 2020-10-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0011_auto_20201027_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(null=True, upload_to="brand"),
        ),
        migrations.AlterField(
            model_name="country",
            name="image",
            field=models.ImageField(null=True, upload_to="country"),
        ),
        migrations.AlterField(
            model_name="season",
            name="image",
            field=models.ImageField(null=True, upload_to="season"),
        ),
        migrations.AlterField(
            model_name="serie",
            name="image",
            field=models.ImageField(null=True, upload_to="serie"),
        ),
    ]
