# Generated by Django 3.1 on 2020-12-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0013_auto_20201027_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
