# Generated by Django 3.1 on 2020-12-23 08:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0014_auto_20201221_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor.fields.RichTextField(default='description'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=ckeditor.fields.RichTextField(default='description'),
        ),
    ]
