# Generated by Django 3.1 on 2020-12-23 08:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0015_auto_20201223_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='description'),
        ),
    ]
