# Generated by Django 3.1 on 2020-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0020_auto_20201225_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='extra_one_year_warranty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
