# Generated by Django 3.1 on 2020-12-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0021_auto_20201225_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='comfort',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='dry',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='noise',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='offroad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='treadware',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serie',
            name='wet',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
