# Generated by Django 3.1 on 2021-01-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0024_brand_show_in_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='snow',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
