# Generated by Django 3.1 on 2021-01-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0026_auto_20210128_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
