# Generated by Django 3.1 on 2021-09-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0029_auto_20210601_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specific.country'),
        ),
    ]
