# Generated by Django 3.1 on 2021-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0031_auto_20210904_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand'),
        ),
    ]
