# Generated by Django 3.1 on 2021-09-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0032_auto_20210904_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='season'),
        ),
    ]
