# Generated by Django 3.2.1 on 2022-01-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0036_auto_20211016_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='free_service',
            new_name='one_year_free_service',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='extra_one_year_warranty',
        ),
        migrations.AddField(
            model_name='brand',
            name='one_year_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='two_year_free_service',
            field=models.BooleanField(default=False),
        ),
    ]
