# Generated by Django 3.2.1 on 2022-06-04 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0037_auto_20220103_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='sub-logo/')),
                ('order', models.PositiveSmallIntegerField(null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specific.brand')),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specific.serie')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
