# Generated by Django 3.2.1 on 2022-06-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0038_sublogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublogo',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_sub_logos', to='specific.brand'),
        ),
        migrations.AlterField(
            model_name='sublogo',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_sub_logos', to='specific.serie'),
        ),
    ]
