# Generated by Django 3.2.1 on 2022-06-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0039_auto_20220604_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublogo',
            name='brand',
        ),
    ]
