# Generated by Django 3.1 on 2021-10-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20210920_0705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TireListMessage',
        ),
    ]
