# Generated by Django 3.2.1 on 2022-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_site', '0003_delete_tirelistmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('r', 'Red'), ('y', 'Yellow'), ('g', 'Gray')], max_length=255, null=True)),
                ('taksit_month', models.PositiveSmallIntegerField(choices=[(2, '2 month'), (3, '3 month'), (6, '6 month'), (9, '9 month'), (12, '12 month')], null=True)),
                ('kredit_month', models.PositiveSmallIntegerField(choices=[(3, '3 month'), (6, '6 month'), (9, '9 month')], null=True)),
            ],
        ),
    ]
