# Generated by Django 3.2.1 on 2022-02-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_rename_pricecolors_pricecolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecolor',
            old_name='kredit_month',
            new_name='kredit',
        ),
        migrations.RenameField(
            model_name='pricecolor',
            old_name='taksit_month',
            new_name='taksit',
        ),
    ]
