# Generated by Django 3.2.1 on 2022-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20220203_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecolor',
            name='kredit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '3 month'), (6, '6 month'), (9, '9 month')], null=True),
        ),
        migrations.AlterField(
            model_name='pricecolor',
            name='taksit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 month'), (3, '3 month'), (6, '6 month'), (9, '9 month'), (12, '12 month')], null=True),
        ),
    ]
