# Generated by Django 3.2.1 on 2022-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_auto_20220203_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecolor',
            name='color',
            field=models.CharField(choices=[('r', 'Red'), ('y', 'Yellow'), ('g', 'Gray')], max_length=255, null=True, unique=True),
        ),
    ]
