# Generated by Django 3.2.1 on 2022-03-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_pricecolor_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManatIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manat')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
