# Generated by Django 3.2.1 on 2022-04-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_manaticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecolor',
            name='switch_to_sale_price',
            field=models.BooleanField(default=False),
        ),
    ]
