# Generated by Django 3.2.1 on 2022-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_pricecolor_switch_to_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricecolor',
            old_name='switch_to_sale_price',
            new_name='use_sale',
        ),
        migrations.AddField(
            model_name='pricecolor',
            name='use_price_3_on_feeless',
            field=models.BooleanField(default=False),
        ),
    ]
