# Generated by Django 3.2.1 on 2022-07-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_sessionkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionkey',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
