# Generated by Django 3.2.1 on 2023-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_alter_sessionkey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireListBottomIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('detail_icon', models.ImageField(null=True, upload_to='detail_icons')),
                ('cart_icon', models.ImageField(null=True, upload_to='cart_icons')),
                ('phone_icon', models.ImageField(null=True, upload_to='phone_icons')),
                ('watsapp_icon', models.ImageField(null=True, upload_to='watsapp_icon')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
