# Generated by Django 3.2.1 on 2023-04-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_tirelistbottomicons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TireListBottomIcons',
            new_name='TireBottomIcons',
        ),
    ]
