# Generated by Django 3.1 on 2021-04-11 18:16

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='campaign/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('extra', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
