# Generated by Django 3.1 on 2021-06-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
