# Generated by Django 3.1 on 2021-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0005_sticker_text_font'),
        ('campaign', '0009_remove_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stickers',
            field=models.ManyToManyField(related_name='posts', to='sticker.Sticker'),
        ),
    ]
