# Generated by Django 3.1 on 2021-06-26 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0014_auto_20210626_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='campaign_video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'mp4'])]),
        ),
    ]
