# Generated by Django 3.2.1 on 2022-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_sessionkey'),
        ('campaign', '0018_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='viewed_by',
            field=models.ManyToManyField(editable=False, to='main_site.SessionKey'),
        ),
    ]
