# Generated by Django 3.1 on 2021-02-27 10:12

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0027_auto_20210129_1254'),
        ('oilapp', '0002_auto_20210227_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='oil')),
                ('des1', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('sale', models.FloatField()),
                ('sale_active', models.BooleanField(default=False)),
                ('taksit_active', models.BooleanField(default=True)),
                ('taksit_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taksit_2_month', models.PositiveSmallIntegerField(default=2)),
                ('taksit_2_active', models.BooleanField(default=True)),
                ('taksit_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taksit_3_month', models.PositiveSmallIntegerField(default=3)),
                ('taksit_3_active', models.BooleanField(default=True)),
                ('taksit_6', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taksit_6_month', models.PositiveSmallIntegerField(default=6)),
                ('taksit_6_active', models.BooleanField(default=True)),
                ('taksit_9', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taksit_9_month', models.PositiveSmallIntegerField(default=9)),
                ('taksit_9_active', models.BooleanField(default=True)),
                ('taksit_12', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taksit_12_month', models.PositiveSmallIntegerField(default=12)),
                ('taksit_12_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oilapp.brand')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specific.country')),
                ('fuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oilapp.fuel')),
                ('oil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oilapp.oiltype')),
                ('viscosity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oilapp.viscosity')),
                ('volume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oilapp.volume')),
            ],
        ),
    ]
