# Generated by Django 3.1 on 2021-06-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0010_auto_20210601_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='albalikart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (3, '3 ay'), (6, '6 ay'), (12, '12 ay')], default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oil',
            name='birkart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oil',
            name='bolkart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oil',
            name='tamkart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], default=1),
            preserve_default=False,
        ),
    ]
