# Generated by Django 3.1 on 2021-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210611_1102'),
        ('sticker', '0005_sticker_text_font'),
        ('oilapp', '0014_oil_campaigns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oil',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='oil',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='oils', to='campaign.Post'),
        ),
        migrations.RemoveField(
            model_name='oil',
            name='stickers',
        ),
        migrations.AddField(
            model_name='oil',
            name='stickers',
            field=models.ManyToManyField(blank=True, related_name='oils', to='sticker.Sticker'),
        ),
    ]
