# Generated by Django 3.2.1 on 2022-03-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit_taksit', '0007_auto_20211016_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredittaksitimage',
            name='description',
            field=models.TextField(default='Qeyd olunan şinləri nağd endirimli qiymətlərdən {{month}} ayadək faizsiz, ilkin ödənişsiz və komissiyasız əldə edə bilərsiniz'),
        ),
        migrations.AddField(
            model_name='kredittaksitimage',
            name='description_az',
            field=models.TextField(default='Qeyd olunan şinləri nağd endirimli qiymətlərdən {{month}} ayadək faizsiz, ilkin ödənişsiz və komissiyasız əldə edə bilərsiniz', null=True),
        ),
        migrations.AddField(
            model_name='kredittaksitimage',
            name='description_en',
            field=models.TextField(default='Qeyd olunan şinləri nağd endirimli qiymətlərdən {{month}} ayadək faizsiz, ilkin ödənişsiz və komissiyasız əldə edə bilərsiniz', null=True),
        ),
        migrations.AddField(
            model_name='kredittaksitimage',
            name='description_ru',
            field=models.TextField(default='Qeyd olunan şinləri nağd endirimli qiymətlərdən {{month}} ayadək faizsiz, ilkin ödənişsiz və komissiyasız əldə edə bilərsiniz', null=True),
        ),
        migrations.AddField(
            model_name='kredittaksitimage',
            name='description_tr',
            field=models.TextField(default='Qeyd olunan şinləri nağd endirimli qiymətlərdən {{month}} ayadək faizsiz, ilkin ödənişsiz və komissiyasız əldə edə bilərsiniz', null=True),
        ),
    ]
