# Generated by Django 3.2.1 on 2023-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit_taksit', '0008_auto_20220308_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kredittaksitimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='taksit-kredit'),
        ),
    ]
