# Generated by Django 3.1 on 2021-07-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_remove_subcontent_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontent',
            name='active',
        ),
    ]
