# Generated by Django 3.1 on 2021-07-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_remove_subcontent_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontent',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='subcontent',
            name='logo',
        ),
    ]
