# Generated by Django 3.1 on 2021-07-23 14:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_auto_20210723_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subcontent',
            name='image',
        ),
        migrations.AlterField(
            model_name='maincontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='subcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
