# Generated by Django 3.1 on 2021-07-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_auto_20210724_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontent',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subcontent',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
