# Generated by Django 3.1 on 2021-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyright', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='content_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='copyright',
            name='content_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='copyright',
            name='content_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='copyright',
            name='content_tr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
