# Generated by Django 3.1 on 2021-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='image_width',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='sticker',
            name='text_width',
            field=models.FloatField(default=50),
        ),
    ]
