# Generated by Django 3.1 on 2021-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0003_sticker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveSmallIntegerField(default=2000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
