# Generated by Django 3.1 on 2021-09-20 07:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0005_sticker_text_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='description_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='text_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='text_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='text_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='text_tr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
