# Generated by Django 3.2.1 on 2022-03-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0008_alter_sticker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
