# Generated by Django 3.1 on 2021-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit', '0003_auto_20210418_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kredittype',
            name='active',
        ),
        migrations.AddField(
            model_name='kredittype',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
