# Generated by Django 3.1 on 2021-04-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit', '0004_auto_20210420_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredittype',
            name='link_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kredittype',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kredittype',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kredittype',
            name='truncate',
            field=models.PositiveSmallIntegerField(default=150),
        ),
    ]
