# Generated by Django 3.1 on 2021-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
