# Generated by Django 3.1 on 2021-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_auto_20210412_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='truncate',
            field=models.PositiveSmallIntegerField(default=150),
        ),
    ]
