# Generated by Django 3.1 on 2021-06-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0005_sticker_text_font'),
        ('campaign', '0010_post_stickers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='stickers',
            field=models.ManyToManyField(blank=True, related_name='posts', to='sticker.Sticker'),
        ),
    ]
