# Generated by Django 3.1 on 2021-06-11 12:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_auto_20210611_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
