# Generated by Django 3.1 on 2021-04-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='link',
            field=models.URLField(),
        ),
    ]
