# Generated by Django 3.1 on 2021-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20210418_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
