# Generated by Django 3.1 on 2021-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_navigationlink_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='title_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='title_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='title_tr',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
