# Generated by Django 3.1 on 2021-10-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_auto_20210920_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationLink',
        ),
    ]
