# Generated by Django 3.1 on 2021-10-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_delete_navigationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('title_az', models.CharField(max_length=20, null=True)),
                ('title_en', models.CharField(max_length=20, null=True)),
                ('title_ru', models.CharField(max_length=20, null=True)),
                ('title_tr', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
                ('order_number', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
