# Generated by Django 3.1 on 2021-10-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_auto_20211002_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationlink',
            old_name='page',
            new_name='link',
        ),
    ]
