# Generated by Django 3.1 on 2021-10-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_navigationlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='link',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
    ]
