# Generated by Django 3.2.1 on 2022-02-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_auto_20211016_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('key', models.CharField(max_length=255, null=True)),
                ('options', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
