# Generated by Django 3.2.1 on 2022-02-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0017_auto_20220216_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationLink',
        ),
    ]
