# Generated by Django 3.2.1 on 2022-02-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0018_delete_navigationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('title_az', models.CharField(max_length=20, null=True)),
                ('title_en', models.CharField(max_length=20, null=True)),
                ('title_ru', models.CharField(max_length=20, null=True)),
                ('title_tr', models.CharField(max_length=20, null=True)),
                ('order_number', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('url_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='navigation.urlname')),
            ],
        ),
    ]
