# Generated by Django 3.1 on 2020-12-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tireapp', '0051_auto_20201123_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(1, 'Nəğd'), (2, 'Kart İlə'), (3, 'Hissə Hissə'), (3, 'Birkart İlə')], default=1)),
                ('is_purchased', models.BooleanField(default=False)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tireapp.tire')),
            ],
        ),
    ]
