# Generated by Django 3.1 on 2020-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nəğd'), (2, 'Kart İlə'), (3, 'Kreditlə'), (4, 'Birkart İlə')], default=1),
        ),
    ]
