# Generated by Django 3.1 on 2021-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_auto_20201224_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nağd'), (2, 'Kart ilə'), (3, 'Kreditlə'), (4, 'BirKart / TamKart ilə')], default=1),
        ),
    ]
