# Generated by Django 3.1 on 2021-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0014_order_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_link',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
