# Generated by Django 3.1 on 2021-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0022_auto_20210608_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilorder',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
