# Generated by Django 3.1 on 2021-06-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0023_auto_20210609_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilorder',
            name='order_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
