# Generated by Django 3.2.1 on 2021-12-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0029_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.AddField(
            model_name='order',
            name='taksit_choice',
            field=models.PositiveSmallIntegerField(choices=[(None, '----'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
