# Generated by Django 3.2.1 on 2021-12-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0030_auto_20211230_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taksit_choice',
            new_name='taksit_choices',
        ),
    ]
