# Generated by Django 3.2.1 on 2021-12-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0036_alter_order_taksit_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='taksit_choices',
            new_name='taksit_choice',
        ),
    ]
