# Generated by Django 3.2.1 on 2022-01-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0038_auto_20211231_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='kapital_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='kapital_session_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
