# Generated by Django 3.2.1 on 2022-01-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0039_auto_20220123_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kapital_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kapital_session_id',
        ),
        migrations.AddField(
            model_name='order',
            name='lang_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
