# Generated by Django 3.2.1 on 2022-02-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0040_auto_20220125_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='change_percentage',
            field=models.FloatField(default=0),
        ),
    ]
