# Generated by Django 3.2.1 on 2022-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0045_auto_20220208_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='by_price_2',
            field=models.BooleanField(default=True),
        ),
    ]
