# Generated by Django 3.2.1 on 2022-02-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0046_alter_order_by_price_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='by_price_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='by_price_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='by_price_3',
        ),
        migrations.AddField(
            model_name='order',
            name='by_price',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Price 1'), (2, 'Price 2'), (3, 'Price 3')], default=2),
        ),
    ]
