# Generated by Django 3.2.1 on 2022-02-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0047_auto_20220208_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='by_amount',
        ),
    ]
