# Generated by Django 3.1 on 2021-01-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='name',
            field=models.CharField(default='advertisement', max_length=50),
        ),
    ]
