# Generated by Django 3.1 on 2021-01-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0002_add_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='duration',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
    ]
