# Generated by Django 3.1 on 2021-09-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0003_auto_20210119_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='image_az',
            field=models.ImageField(null=True, upload_to='add'),
        ),
        migrations.AddField(
            model_name='add',
            name='image_en',
            field=models.ImageField(null=True, upload_to='add'),
        ),
        migrations.AddField(
            model_name='add',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='add'),
        ),
        migrations.AddField(
            model_name='add',
            name='image_tr',
            field=models.ImageField(null=True, upload_to='add'),
        ),
    ]
