# Generated by Django 3.1 on 2021-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0004_auto_20210920_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(null=True, upload_to='add'),
        ),
    ]
