# Generated by Django 3.1 on 2021-01-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faviconapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='icon',
            field=models.FileField(upload_to='favicon'),
        ),
    ]
