# Generated by Django 3.1 on 2020-09-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0003_auto_20200905_0924"),
        ("tireapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tire",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.brand",
            ),
        ),
        migrations.AddField(
            model_name="tire",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tire",
            name="image",
            field=models.ImageField(default="default.png", upload_to="product"),
        ),
        migrations.AddField(
            model_name="tire",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.country",
            ),
        ),
        migrations.AddField(
            model_name="tire",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.season",
            ),
        ),
        migrations.AddField(
            model_name="tire",
            name="serie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.serie",
            ),
        ),
        migrations.AddField(
            model_name="tire",
            name="title",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
