# Generated by Django 3.1 on 2020-09-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0002_auto_20200905_0924"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tire",
        ),
    ]
