# Generated by Django 3.1 on 2020-09-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0004_tire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.CharField(max_length=10, null=True)),
                ("height", models.CharField(max_length=10, null=True)),
                ("radius", models.CharField(max_length=10, null=True)),
                ("ZR_R", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="tire",
            name="size",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tireapp.size",
            ),
        ),
    ]
