# Generated by Django 3.1 on 2020-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0005_auto_20200905_1011"),
    ]

    operations = [
        migrations.AddField(
            model_name="tire",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
    ]
