# Generated by Django 3.1 on 2020-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0006_tire_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tire",
            name="size",
        ),
        migrations.AddField(
            model_name="tire",
            name="ZR_R",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tire",
            name="height",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tire",
            name="radius",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tire",
            name="width",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="Size",
        ),
    ]
