# Generated by Django 3.1 on 2020-09-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0008_auto_20200907_0811"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tire",
            name="title",
        ),
        migrations.AlterField(
            model_name="tire",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tireapp.size",
            ),
        ),
    ]
