# Generated by Django 3.1 on 2020-09-13 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tireapp", "0012_tire_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="tire",
            name="updater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="updater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
