# Generated by Django 3.1 on 2020-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0014_auto_20200915_1009"),
    ]

    operations = [
        migrations.AddField(
            model_name="tire",
            name="created_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
