# Generated by Django 3.1 on 2020-09-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0016_auto_20200922_0858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="USDNO",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="pricedifference",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
