# Generated by Django 3.1 on 2020-09-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0003_auto_20200905_0924"),
        ("tireapp", "0017_auto_20200923_2038"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tire",
            name="season",
        ),
        migrations.AddField(
            model_name="selectfilter",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="specific.season",
            ),
        ),
    ]
