# Generated by Django 3.1 on 2020-09-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0020_auto_20200925_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="filters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tireapp.filter",
            ),
        ),
    ]
