# Generated by Django 3.1 on 2020-09-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0003_auto_20200905_0924"),
        ("tireapp", "0021_auto_20200925_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="filters",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.filter",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="manufacturer",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.country",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="size",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.size",
            ),
        ),
    ]
