# Generated by Django 3.1 on 2020-09-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0024_auto_20200927_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kreditbox",
            name="month_12",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_12",
                to="tireapp.kredit",
            ),
        ),
        migrations.AlterField(
            model_name="kreditbox",
            name="month_3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_3",
                to="tireapp.kredit",
            ),
        ),
        migrations.AlterField(
            model_name="kreditbox",
            name="month_6",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_6",
                to="tireapp.kredit",
            ),
        ),
        migrations.AlterField(
            model_name="kreditbox",
            name="month_9",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_9",
                to="tireapp.kredit",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="USD",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT, to="tireapp.sale"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="USDOFF",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.pricedifference",
            ),
        ),
        migrations.AlterField(
            model_name="taksitbox",
            name="month_12",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_12",
                to="tireapp.taksit",
            ),
        ),
        migrations.AlterField(
            model_name="taksitbox",
            name="month_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_2",
                to="tireapp.taksit",
            ),
        ),
        migrations.AlterField(
            model_name="taksitbox",
            name="month_3",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_3",
                to="tireapp.taksit",
            ),
        ),
        migrations.AlterField(
            model_name="taksitbox",
            name="month_6",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_6",
                to="tireapp.taksit",
            ),
        ),
        migrations.AlterField(
            model_name="taksitbox",
            name="month_9",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="month_9",
                to="tireapp.taksit",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="extra",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.extra",
            ),
        ),
    ]
