# Generated by Django 3.1 on 2020-09-30 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0004_auto_20200928_1446"),
        ("tireapp", "0029_auto_20200927_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectfilter",
            name="season",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.season",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.brand",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.country",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="serie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="specific.serie",
            ),
        ),
    ]
