# Generated by Django 3.1 on 2020-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0030_auto_20200930_1355"),
    ]

    operations = [
        migrations.AddField(
            model_name="kredit",
            name="p_dif",
            field=models.FloatField(default=0),
        ),
    ]
