# Generated by Django 3.1 on 2020-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0031_kredit_p_dif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectfilter",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
