# Generated by Django 3.1 on 2020-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0034_auto_20201004_1034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="image",
            field=models.ImageField(default="default.png", upload_to="product"),
        ),
    ]
