# Generated by Django 3.1 on 2020-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0037_auto_20201004_1117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="USD",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="tire",
            name="USDOFF",
            field=models.FloatField(default=0),
        ),
    ]
