# Generated by Django 3.1 on 2020-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0038_auto_20201004_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="kredit_12_month",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="tire",
            name="kredit_3_month",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="tire",
            name="kredit_6_month",
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="tire",
            name="kredit_9_month",
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_12_month",
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_2_month",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_3_month",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_6_month",
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_9_month",
            field=models.PositiveSmallIntegerField(default=9),
        ),
    ]
