# Generated by Django 3.1 on 2020-10-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0043_auto_20201005_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="kredit_12",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="kredit_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="kredit_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="kredit_9",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="montaj_balance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="razval",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_12",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_2",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_6",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="taksit_9",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
