# Generated by Django 3.1 on 2020-10-06 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0006_auto_20201003_1025"),
        ("tireapp", "0044_auto_20201005_1513"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="specific.brand",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="manufacturer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="specific.country",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="serie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="specific.serie",
            ),
        ),
    ]
