# Generated by Django 3.1 on 2020-10-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0045_auto_20201006_0853"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tire",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tire",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="tire",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="tire",
            name="updater",
        ),
    ]
