# Generated by Django 3.1 on 2020-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0048_auto_20201006_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="product"),
        ),
    ]
