# Generated by Django 3.1 on 2020-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0049_auto_20201027_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="radius",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="size",
            name="width",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
