# Generated by Django 3.1 on 2020-11-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0050_auto_20201030_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='image',
            field=models.ImageField(default='default.png', upload_to='product'),
        ),
    ]
