# Generated by Django 3.1 on 2020-12-22 13:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0053_auto_20201222_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='description',
            field=ckeditor.fields.RichTextField(default='description'),
        ),
    ]
