# Generated by Django 3.1 on 2020-12-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0054_auto_20201222_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='description',
        ),
    ]
