# Generated by Django 3.1 on 2020-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0057_auto_20201226_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='OE',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
