# Generated by Django 3.1 on 2020-12-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0058_auto_20201228_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default-tire', models.ImageField(upload_to='default')),
            ],
        ),
        migrations.AlterField(
            model_name='tire',
            name='image',
            field=models.ImageField(default='default/default-tire.png', upload_to='product'),
        ),
    ]
