# Generated by Django 3.1 on 2021-01-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0063_auto_20210105_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
