# Generated by Django 3.1 on 2021-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0065_auto_20210111_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='release_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tire',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
