# Generated by Django 3.1 on 2021-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0066_auto_20210115_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='release_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
