# Generated by Django 3.1 on 2021-01-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0067_auto_20210115_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='contact',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='tire',
            name='db',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tire',
            name='fuel',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
