# Generated by Django 3.1 on 2021-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0068_auto_20210125_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='db',
            field=models.PositiveSmallIntegerField(default=72),
        ),
    ]
