# Generated by Django 3.1 on 2021-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0070_auto_20210125_0901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultImage',
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit_initial_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
