# Generated by Django 3.1 on 2021-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0071_auto_20210126_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='kredit_12_dif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_3_dif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_6_dif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_9_dif',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
