# Generated by Django 3.1 on 2021-02-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0074_auto_20210127_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='image',
        ),
    ]
