# Generated by Django 3.1 on 2021-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0076_auto_20210501_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
