# Generated by Django 3.1 on 2021-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0077_tire_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
