# Generated by Django 3.1 on 2021-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0078_auto_20210512_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='max_razval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
