# Generated by Django 3.1 on 2021-05-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0079_tire_max_razval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='max_razval',
        ),
    ]
