# Generated by Django 3.1 on 2021-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0080_remove_tire_max_razval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='razval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
