# Generated by Django 3.1 on 2021-05-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0081_auto_20210513_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneSTire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='XXX', max_length=200)),
                ('tire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_s_tire', to='tireapp.tire')),
            ],
        ),
    ]
