# Generated by Django 3.1 on 2021-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0085_onestire_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestire',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
