# Generated by Django 3.1 on 2021-05-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0089_auto_20210522_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onestire',
            name='quantity',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
