# Generated by Django 3.1 on 2021-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0091_auto_20210601_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
