# Generated by Django 3.1 on 2021-06-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0093_auto_20210601_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='kredit_12_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='kredit_3_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='kredit_6_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='kredit_9_month',
        ),
    ]
