# Generated by Django 3.1 on 2021-06-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0100_auto_20210602_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='albalikart',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (3, 3), (6, 6), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='tire',
            name='birkart',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2), (3, 3), (6, 6), (9, 9), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='tire',
            name='bolkart',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2), (3, 3), (6, 6), (9, 9), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (3, 3), (6, 6), (9, 9), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='tire',
            name='tamkart',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (2, 2), (3, 3), (6, 6), (9, 9), (12, 12)]),
        ),
    ]
