# Generated by Django 3.1 on 2021-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0103_auto_20210602_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='albalikart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')]),
        ),
    ]
