# Generated by Django 3.1 on 2021-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0109_auto_20210611_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tire',
            old_name='campaings',
            new_name='campaigns',
        ),
    ]
