# Generated by Django 3.1 on 2021-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0111_auto_20210611_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='campaigns',
        ),
        migrations.AddField(
            model_name='tire',
            name='campaigns',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='tire',
            name='stickers',
        ),
        migrations.AddField(
            model_name='tire',
            name='stickers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
