# Generated by Django 3.1 on 2021-08-20 08:05

from django.db import migrations, models
import tireapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0114_tire_price_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='size_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
