# Generated by Django 3.1 on 2021-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0116_ostireimportersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='oe')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'OE',
                'verbose_name_plural': 'OE',
            },
        ),
        migrations.DeleteModel(
            name='OneSTire',
        ),
    ]
