# Generated by Django 3.1 on 2021-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0117_auto_20210904_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oe',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
