# Generated by Django 3.1 on 2021-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0118_auto_20210904_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='oe',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
