# Generated by Django 3.1 on 2021-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0119_oe_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oe',
            name='key',
        ),
    ]
