# Generated by Django 3.1 on 2021-09-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0120_remove_oe_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2017)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tire',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
