# Generated by Django 3.1 on 2021-09-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0122_auto_20210906_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tireapp.tireclass'),
        ),
    ]
