# Generated by Django 3.1 on 2021-09-06 06:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0124_auto_20210906_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oe',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
