# Generated by Django 3.1 on 2021-09-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0127_auto_20210920_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='speed',
            field=models.CharField(blank=True, default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tire',
            name='weight',
            field=models.IntegerField(blank=True, default=90),
            preserve_default=False,
        ),
    ]
