# Generated by Django 3.1 on 2021-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0128_auto_20210920_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='quantity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
