# Generated by Django 3.1 on 2021-09-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0129_auto_20210920_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
