# Generated by Django 3.1 on 2021-10-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0035_auto_20210920_0705'),
        ('tireapp', '0130_auto_20210920_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='OE',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='tire',
            name='albalikart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='birkart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='bolkart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specific.brand'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='contact',
            field=models.CharField(default='B', max_length=255),
        ),
        migrations.AlterField(
            model_name='tire',
            name='fuel',
            field=models.CharField(default='B', max_length=255),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specific.country'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='montaj_balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='razval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='release_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='sale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specific.season'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specific.serie'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tireapp.size'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='tamkart',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yoxdur'), (2, '2 ay'), (3, '3 ay'), (6, '6 ay'), (9, '9 ay'), (12, '12 ay')], null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='tire_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tireapp.tireclass'),
        ),
    ]
