# Generated by Django 3.2.1 on 2021-10-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0132_auto_20211018_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='radius',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
