# Generated by Django 3.2.1 on 2021-11-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0133_auto_20211030_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='trim_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
