# Generated by Django 3.2.1 on 2021-11-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0134_tire_trim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='OE',
            field=models.CharField(default='-', max_length=255, null=True),
        ),
    ]
