# Generated by Django 3.2.1 on 2021-12-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0136_auto_20211120_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'ordering': ('-brand__order_number',)},
        ),
    ]
