# Generated by Django 3.2.1 on 2022-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0138_auto_20220107_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='price_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
