# Generated by Django 3.2.1 on 2022-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0139_alter_tire_price_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='sale_active',
        ),
        migrations.AddField(
            model_name='tire',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
