# Generated by Django 3.2.1 on 2022-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0141_alter_tire_tradeware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='radius',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
