# Generated by Django 3.2.1 on 2022-04-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0142_auto_20220301_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'ordering': ('-brand__order_number', '-order_number')},
        ),
        migrations.AddField(
            model_name='tire',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
