# Generated by Django 3.2.1 on 2022-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0143_auto_20220407_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='contact',
            field=models.CharField(default='B', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='fuel',
            field=models.CharField(default='B', max_length=255, null=True),
        ),
    ]
