# Generated by Django 3.2.1 on 2022-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0144_auto_20220407_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='international_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tireclass',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
