# Generated by Django 3.2.1 on 2022-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0145_auto_20220421_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='kredit_4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit_4_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit_4_dif',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit_5_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit_5_dif',
            field=models.FloatField(default=0),
        ),
    ]
