# Generated by Django 3.2.1 on 2022-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0146_auto_20220428_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='kredit_3_month_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_6_month_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
