# Generated by Django 3.2.1 on 2022-06-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0147_auto_20220604_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'ordering': ('-brand__order_number',)},
        ),
    ]
