# Generated by Django 3.2.1 on 2022-06-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0149_alter_tire_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tire',
            options={'ordering': ('order_number', '-brand__order_number')},
        ),
    ]
