# Generated by Django 3.2.1 on 2022-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0150_alter_tire_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
