# Generated by Django 3.2.1 on 2022-06-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0151_alter_tire_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='kredit_12_dif',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_3_dif',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_4_dif',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_5_dif',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_6_dif',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_9_dif',
            field=models.FloatField(default=0, null=True),
        ),
    ]
