# Generated by Django 3.2.1 on 2022-09-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0152_auto_20220612_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
