# Generated by Django 3.1 on 2021-02-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0013_auto_20210212_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
