# Generated by Django 3.1 on 2021-03-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0075_remove_tire_image'),
        ('ordering', '0016_auto_20210306_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TireOrder',
            new_name='Order',
        ),
    ]
