# Generated by Django 3.1 on 2021-03-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_auto_20210306_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilorder',
            name='quantity',
        ),
    ]
