# Generated by Django 3.1 on 2021-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0020_remove_oilorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilorder',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nağd'), (2, 'Kart ilə'), (3, 'BirKart / TamKart ilə')], default=1),
        ),
    ]
