# Generated by Django 3.1 on 2021-08-20 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='wincode',
            field=models.CharField(max_length=255, null=True, verbose_name='Win | Ban'),
        ),
        migrations.AlterField(
            model_name='warrantytalon',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
