# Generated by Django 3.1 on 2021-08-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0003_auto_20210820_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='year_service',
            field=models.BooleanField(default=False, verbose_name='1 il servis'),
        ),
    ]
