# Generated by Django 3.1 on 2021-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0015_auto_20210820_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='car_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Maşın nömrə'),
        ),
    ]
