# Generated by Django 3.1 on 2021-08-21 06:02

from django.db import migrations, models
import django.db.models.deletion
import mysite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0017_auto_20210821_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='İstehsal il'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='gold_warranty',
            field=models.BooleanField(default=False, verbose_name='Qızıl zemanət'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='phone',
            field=models.CharField(max_length=255, null=True, validators=[mysite.validators.PhoneValidator], verbose_name='Telefon nomrə'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='warranty_talon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_info', to='waranty.warrantytalon'),
        ),
        migrations.AlterField(
            model_name='cartire',
            name='warranty_talon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_tire', to='waranty.warrantytalon'),
        ),
    ]
