# Generated by Django 3.1 on 2021-08-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0018_auto_20210821_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='warranty_talon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_info', to='waranty.warrantytalon'),
        ),
        migrations.AlterField(
            model_name='cartire',
            name='warranty_talon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_tire', to='waranty.warrantytalon'),
        ),
    ]
