# Generated by Django 3.1 on 2021-08-21 06:07

from django.db import migrations, models
import mysite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0019_auto_20210821_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad | Soyad'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage | km'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[mysite.validators.PhoneValidator], verbose_name='Telefon nomrə'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='wincode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Win | Ban'),
        ),
    ]
