# Generated by Django 3.1 on 2021-08-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0021_auto_20210821_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('child_of', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
