# Generated by Django 3.1 on 2021-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0023_payment_has_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
