# Generated by Django 3.1 on 2021-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0024_payment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='payment',
            name='key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
