# Generated by Django 3.1 on 2020-09-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0004_auto_20200928_1446"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="specific.country"
            ),
        ),
        migrations.AlterField(
            model_name="serie",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="specific.brand"
            ),
        ),
    ]
