# Generated by Django 3.1 on 2020-10-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0007_brand_order_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="order_count",
        ),
    ]
