# Generated by Django 3.1 on 2020-10-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specific", "0012_auto_20201027_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="country"),
        ),
    ]
