# Generated by Django 3.1 on 2020-12-25 17:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0022_auto_20201225_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='extra',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
