# Generated by Django 3.1 on 2021-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0023_serie_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_in_slider',
            field=models.BooleanField(default=False),
        ),
    ]
