# Generated by Django 3.1 on 2021-01-28 10:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0025_serie_snow'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]