# Generated by Django 3.1 on 2021-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0027_auto_20210129_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='serie'),
        ),
    ]
