# Generated by Django 3.1 on 2021-06-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0028_auto_20210512_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serie',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
