# Generated by Django 3.1 on 2021-05-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_address_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
