# Generated by Django 3.1 on 2021-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20210515_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, upload_to='map'),
        ),
    ]
