# Generated by Django 3.1 on 2021-06-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticker', '0004_stickertimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='text_font',
            field=models.PositiveSmallIntegerField(default=16),
        ),
    ]
