# Generated by Django 3.1 on 2021-02-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make',
            name='active',
        ),
        migrations.RemoveField(
            model_name='make',
            name='name',
        ),
        migrations.RemoveField(
            model_name='make',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='model',
            name='active',
        ),
        migrations.RemoveField(
            model_name='model',
            name='name',
        ),
        migrations.RemoveField(
            model_name='model',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='active',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trim',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='year',
            name='active',
        ),
        migrations.RemoveField(
            model_name='year',
            name='name',
        ),
        migrations.RemoveField(
            model_name='year',
            name='slug',
        ),
    ]
