# Generated by Django 3.1 on 2021-02-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0002_auto_20210203_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Trim',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
