# Generated by Django 3.1 on 2021-02-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0004_make_model_trim_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.make'),
        ),
        migrations.AlterField(
            model_name='trim',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.make'),
        ),
        migrations.AlterField(
            model_name='trim',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.model'),
        ),
        migrations.AlterField(
            model_name='trim',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.make'),
        ),
        migrations.AlterField(
            model_name='year',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.model'),
        ),
    ]
