# Generated by Django 3.1 on 2021-02-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0006_tiresize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TireSize',
        ),
    ]
