# Generated by Django 3.1 on 2021-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0008_tiresize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiresize',
            name='tire_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'front'), (2, 'rear'), (3, '4x4')]),
        ),
    ]
