# Generated by Django 3.1 on 2021-06-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_advpercentage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ADVLogo',
            new_name='EDVLogo',
        ),
        migrations.RenameModel(
            old_name='ADVPercentage',
            new_name='EDVPercentage',
        ),
    ]
