# Generated by Django 3.1 on 2021-06-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_auto_20210627_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edvlogo',
            old_name='avtive',
            new_name='active',
        ),
    ]
