# Generated by Django 3.1 on 2021-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20201226_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('youtube', 'youtube')], max_length=30),
        ),
    ]
