# Generated by Django 3.1 on 2021-05-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20210205_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latidude',
            field=models.FloatField(default=40.40432361546929),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=49.877367169701486),
        ),
    ]
