# Generated by Django 3.1 on 2021-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210514_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
