# Generated by Django 3.1 on 2021-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_address_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
