# Generated by Django 3.2.1 on 2022-07-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20220721_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_image',
            field=models.ImageField(null=True, upload_to='map'),
        ),
        migrations.AddField(
            model_name='address',
            name='zoom',
            field=models.FloatField(default=17, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='latidude',
            field=models.FloatField(default=40.40432361546929, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.FloatField(default=49.877367169701486, null=True),
        ),
    ]
