# Generated by Django 3.1 on 2021-07-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_auto_20210723_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcontent',
            name='title',
        ),
    ]
