# Generated by Django 3.1 on 2021-07-24 11:47

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0007_auto_20210723_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maincontent',
            name='heading',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcontent',
            name='heading',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
