# Generated by Django 3.1 on 2021-06-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_https', models.BooleanField(default=False)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='secure_site', to='sites.site')),
            ],
        ),
    ]
