# Generated by Django 3.1 on 2021-06-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securesite',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
