# Generated by Django 3.1 on 2021-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viscosity',
            options={'verbose_name_plural': 'Viscosities'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='show_in_slider',
            field=models.BooleanField(default=True),
        ),
    ]
