# Generated by Django 3.1 on 2021-02-27 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0003_oil'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='oil',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oilapp.serie'),
        ),
    ]
