# Generated by Django 3.1 on 2021-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0005_auto_20210227_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
