# Generated by Django 3.1 on 2021-06-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0006_oil_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
