# Generated by Django 3.1 on 2021-06-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specific', '0028_auto_20210512_1303'),
        ('oilapp', '0008_serie_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oil',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oilapp.brand'),
        ),
        migrations.AlterField(
            model_name='oil',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specific.country'),
        ),
        migrations.AlterField(
            model_name='oil',
            name='fuel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='oil_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oilapp.serie'),
        ),
        migrations.AlterField(
            model_name='oil',
            name='viscosity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='volume',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
        migrations.DeleteModel(
            name='OilType',
        ),
        migrations.DeleteModel(
            name='Viscosity',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
