# Generated by Django 3.2.1 on 2022-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilapp', '0017_auto_20211016_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oil',
            name='sale_active',
        ),
        migrations.AddField(
            model_name='oil',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oil',
            name='sale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
