# Generated by Django 3.2.1 on 2022-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_sessionkey'),
        ('news', '0006_news_viewed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='viewed_by',
        ),
        migrations.AddField(
            model_name='news',
            name='viewed_by',
            field=models.ManyToManyField(to='main_site.SessionKey'),
        ),
    ]
