# Generated by Django 3.2.1 on 2022-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_sessionkey'),
        ('news', '0008_alter_news_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='viewed_by',
            field=models.ManyToManyField(editable=False, to='main_site.SessionKey'),
        ),
    ]
