# Generated by Django 3.1 on 2021-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
