# Generated by Django 3.1 on 2021-04-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kredit', '0002_auto_20210418_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kredittype',
            name='link',
        ),
        migrations.RemoveField(
            model_name='kredittype',
            name='link_active',
        ),
        migrations.RemoveField(
            model_name='kredittype',
            name='link_title',
        ),
    ]
