# Generated by Django 3.1 on 2021-04-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kredit', '0005_auto_20210421_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KreditType',
            new_name='Kredit',
        ),
    ]
