# Generated by Django 3.2.1 on 2022-01-25 09:55

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kapital_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kapitalpaymentsecurity',
            name='crt_file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='crt/'),
        ),
        migrations.AlterField(
            model_name='kapitalpaymentsecurity',
            name='key_file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='key/'),
        ),
    ]
