# Generated by Django 3.2.1 on 2022-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapital_bank', '0002_auto_20220125_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapitalpaymentsecurity',
            name='service_link',
            field=models.CharField(default='https://e-commerce.kapitalbank.az:5443/Exec', max_length=255),
        ),
    ]
