# Generated by Django 3.2.1 on 2022-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapital_bank', '0003_kapitalpaymentsecurity_service_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='kapitalpaymentsecurity',
            name='merchant_id',
            field=models.CharField(default='E1000010', max_length=255),
        ),
        migrations.AddField(
            model_name='kapitalpaymentsecurity',
            name='payment_link',
            field=models.CharField(default='https://e-commerce.kapitalbank.az/index.jsp?ORDERID={{ORDERID}}&SESSIONID={{SESSIONID}}', max_length=255),
        ),
    ]
