# Generated by Django 3.1 on 2020-09-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0025_auto_20200927_0749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="filters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.filter",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="select_filters",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.selectfilter",
            ),
        ),
        migrations.AlterField(
            model_name="tire",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tireapp.size",
            ),
        ),
    ]
