# Generated by Django 3.1 on 2020-10-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0035_auto_20201004_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="radius",
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="width",
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
