# Generated by Django 3.1 on 2020-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tireapp", "0036_auto_20201004_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tire",
            name="radius",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="tire",
            name="width",
            field=models.IntegerField(null=True),
        ),
    ]
