# Generated by Django 3.1 on 2020-12-21 20:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0051_auto_20201123_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='description',
            field=ckeditor.fields.RichTextField(default='description'),
        ),
    ]
