# Generated by Django 3.1 on 2020-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0055_remove_tire_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='USDOFF_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='USD_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_12_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_6_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_9_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='kredit_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_12_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_3_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_6_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_9_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tire',
            name='taksit_active',
            field=models.BooleanField(default=False),
        ),
    ]
