# Generated by Django 3.1 on 2020-12-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0059_auto_20201231_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultimage',
            old_name='default-tire',
            new_name='image',
        ),
    ]
