# Generated by Django 3.1 on 2021-01-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0061_auto_20201231_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
