# Generated by Django 3.1 on 2021-01-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0069_auto_20210125_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='contact',
            field=models.CharField(default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='tire',
            name='fuel',
            field=models.CharField(default='B', max_length=5),
        ),
    ]
