# Generated by Django 3.1 on 2021-05-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0075_remove_tire_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tire',
            old_name='USDNO',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='tire',
            old_name='USD',
            new_name='sale',
        ),
        migrations.RenameField(
            model_name='tire',
            old_name='USDOFF_active',
            new_name='sale_active',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='USDOFF',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='USD_active',
        ),
    ]
