# Generated by Django 3.1 on 2021-05-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0082_onestire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onestire',
            name='tire',
        ),
        migrations.AddField(
            model_name='onestire',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onestire',
            name='price_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='onestire',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onestire',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='tire',
            name='code',
            field=models.CharField(default='XXX', max_length=200),
        ),
    ]
