# Generated by Django 3.1 on 2021-06-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0092_tire_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tire',
            name='taksit_12_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='taksit_2_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='taksit_3_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='taksit_6_month',
        ),
        migrations.RemoveField(
            model_name='tire',
            name='taksit_9_month',
        ),
    ]
