# Generated by Django 3.1 on 2021-06-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0094_auto_20210601_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
