# Generated by Django 3.1 on 2021-06-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0096_auto_20210601_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='razval',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
