# Generated by Django 3.1 on 2021-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0097_auto_20210601_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='albalikart',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (6, 6), (9, 9), (12, 12)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='birkart',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (6, 6), (9, 9), (12, 12)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='bolkart',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (6, 6), (9, 9), (12, 12)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='kredit',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (6, 6), (9, 9), (12, 12)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tire',
            name='tamkart',
            field=models.PositiveSmallIntegerField(choices=[(2, 2), (3, 3), (6, 6), (9, 9), (12, 12)], default=1),
            preserve_default=False,
        ),
    ]
