# Generated by Django 3.1 on 2021-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0105_auto_20210604_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
