# Generated by Django 3.1 on 2021-06-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0107_tire_stickers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='campains',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
