# Generated by Django 3.1 on 2021-08-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0113_auto_20210816_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='price_3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
