# Generated by Django 3.1 on 2021-08-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0115_size_size_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsTireImporterSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look_up', models.CharField(max_length=100, null=True)),
                ('get_from_field', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
