# Generated by Django 3.1 on 2021-02-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0005_auto_20210203_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire_type', models.PositiveSmallIntegerField(choices=[(1, 'front'), (2, 'rear')])),
                ('tire', models.CharField(max_length=15)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.model')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.trim')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheel_size.year')),
            ],
        ),
    ]
