# Generated by Django 3.1 on 2021-02-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_size', '0009_auto_20210204_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiresize',
            name='pressure',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
