# Generated by Django 3.1 on 2021-08-20 07:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tireapp', '0114_tire_price_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyTalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tireapp.tire')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), app.validators.ContentTypeValidator(mime_types=['application/pdf'])])),
                ('active', models.BooleanField(default=True)),
                ('warranty_talon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waranty.warrantytalon')),
            ],
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='Ad | Soyad')),
                ('mileage', models.PositiveSmallIntegerField(null=True, verbose_name='Mileage | km')),
                ('wincode', models.CharField(max_length=255, null=True)),
                ('car_make', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marka')),
                ('car_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('car_moter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motor')),
                ('car_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Istehsal il')),
                ('year_service', models.BooleanField(default=False, verbose_name='1il servis')),
                ('gold_warranty', models.BooleanField(default=False, verbose_name='Qizil zemanet')),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waranty.cartype', verbose_name='Tip')),
            ],
        ),
    ]
