# Generated by Django 3.1 on 2021-08-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tireapp', '0115_size_size_code'),
        ('waranty', '0004_auto_20210820_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartire',
            name='tire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tireapp.tire'),
        ),
        migrations.AlterField(
            model_name='cartire',
            name='warranty_talon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='waranty.warrantytalon'),
        ),
    ]
