# Generated by Django 3.1 on 2021-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0006_auto_20210820_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartire',
            name='disk_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartire',
            name='montaj_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartire',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='cartire',
            name='razval',
            field=models.BooleanField(default=True),
        ),
    ]
