# Generated by Django 3.1 on 2021-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0007_auto_20210820_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantytalon',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
