# Generated by Django 3.1 on 2021-08-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0010_auto_20210820_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantytalon',
            name='title',
        ),
    ]
