# Generated by Django 3.1 on 2021-08-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0014_auto_20210820_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='mileage',
            field=models.PositiveIntegerField(null=True, verbose_name='Mileage | km'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='warranty_talon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_set', to='waranty.warrantytalon'),
        ),
    ]
