# Generated by Django 3.1 on 2021-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0022_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
    ]
