# Generated by Django 3.1 on 2021-08-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0026_auto_20210821_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartire',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waranty.payment'),
        ),
    ]
