# Generated by Django 3.1 on 2021-08-23 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waranty', '0028_auto_20210823_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartire',
            name='payment',
            field=models.ForeignKey(limit_choices_to={'has_childs': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waranty.payment'),
        ),
    ]
