# Generated by Django 3.1 on 2021-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KreditTaksitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='taksit-kredit')),
                ('name', models.CharField(choices=[('birkart', 'Birkart'), ('tamkart', 'Tamkart'), ('bolkart', 'Bolkart'), ('albalikart', 'Albalikart'), ('kredit', 'kredit')], max_length=20)),
            ],
        ),
    ]
