# Generated by Django 3.1 on 2021-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit_taksit', '0003_auto_20210602_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='KreditTaksitInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('interval', models.PositiveSmallIntegerField(default=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kredittaksitimage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
