# Generated by Django 3.1 on 2021-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredit_taksit', '0005_auto_20210603_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='kredittaksitinterval',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
